### ISSUE TITLE
ControlPanel: Performance | Schema modification and forms update

### ISSUE THREAD

**Issue by brucelane** [gianlucadelgobbo/AVnode.net#10]
From https://github.com/avnode/avnode/issues/5
```about: String,``` we need it multilang -> Array?
```is_public: Boolean,``` Missing

We need categories and are related if mapping the second level could be generative and the third tecno, if first is workshop, second could not exist
```categories: [],```

```tech_art: String,``` Missing: what the artist bring

```tech_req: String,```  Missing: what the artist need

```video: { type: Schema.ObjectId, ref: 'Asset' }``` We need galleries...

```galleries: [Gallery],``` to be defined, see https://github.com/gianlucadelgobbo/AVnode.net/issues/9

```events: [{ type : Schema.ObjectId, ref : 'Event' }],``` We need the info about the schedule, see https://github.com/gianlucadelgobbo/AVnode.net/issues/8

**Comment by gianlucadelgobbo** [comment]
yes

**Comment by brucelane** [comment]
```about: String,``` done with array of About schema, multilang
```is_public: Boolean,``` created
```tech_art: String,``` created
```tech_req: String,```  created

**Comment by brucelane** [comment]
new bug: video field disappear if someone clicks on the Add video button with a blank link

**Comment by brucelane** [comment]
tech_req is an array (multilang) in the flxer import, a string here, shall we keep it multilang?
