### ISSUE TITLE
ControlPanel: Crews | Apply for an existing crew

### ISSUE THREAD

**Issue by brucelane** [gianlucadelgobbo/AVnode.net#13]
From https://github.com/avnode/avnode/issues/8
Needs to be verified by members of the crew…

**Comment by gianlucadelgobbo** [comment]
Usually is the opposite, you add someone and that one have to accept

**Comment by brucelane** [comment]
galleries: [{ type : Schema.ObjectId, ref : 'Gallery' }] added
