### ISSUE TITLE
Route & redux error

### ISSUE THREAD

**Issue by gianlucadelgobbo** [gianlucadelgobbo/AVnode.net#138]
MOLTO STRANO DOVETE CONTROLLARE
--
http://localhost:8006/nikky/STOCAZZO
dice che la route non c'è
ok, bon la metto alla fine come caso non risolto dentro le root dell'utente /:user diciamo
```
router.get('/*', (req, res) => {
  res.status(404).render...
});
```
il boundle.js si rompe, ma cosa c'entra????
la route commentata sta qui
app/routes/performers/show.js

**Comment by gianlucadelgobbo** [comment]
Solved?

**Comment by piero80** [comment]
No. I saw but I don't understand why.

**Comment by gianlucadelgobbo** [comment]
Solved? @danielesalvatore can you checkit?
