### ISSUE TITLE
ControlPanel: Password

### ISSUE THREAD

**Issue by gianlucadelgobbo** [gianlucadelgobbo/AVnode.net#140]
Only old password is sent

Validation parameters where they are coming from? How to manage it?

**Comment by danielesalvatore** [comment]
@gianlucadelgobbo the payload of the PUT  on `/admin/api/profile/password` is now 
`{oldpassword: "poi", password: "asd", _id: "5a9c57d560662400000160eb"}`

where:
- _id: is the ID of the logged in user
- password: the new password
- oldpassword: the old password

Is this how the server expects it? It seems to me that the server doesn't take into consideration the `oldpassword` check.

Client-side password validation is performed [here](https://github.com/gianlucadelgobbo/AVnode.net/blob/develop/app/redux/components/profile/password/validate.js#L14) and of course it can be expanded with a server-side validation too

**Comment by gianlucadelgobbo** [comment]
Server side errors are ignored test trying to change password to ```070190Gi```

Server side done, please change:
```password```: the new password
to
```newpassword```: the new password

Let me check serverside too newpasswordconfirm, please add ```newpasswordconfirm```

**Comment by danielesalvatore** [comment]
@gianlucadelgobbo I just renamed the `password` param to `newpassword` and added the `newpasswordconfirm ` param to the request payload (`PUT api/profile/password`).

I still cannot get a server side error from the form submission.
Please find below a screenshot in witch I get a `200 Success Code` while trying to change the password sending back to the server a *wrong* `oldpassword`

<img width="1440" alt="screen shot 2018-09-22 at 10 09 31" src="https://user-images.githubusercontent.com/6150475/45915116-cca72500-be4f-11e8-8bd1-591662d3a068.png">

**Comment by gianlucadelgobbo** [comment]
new password check  server error works
old password check not
![screen shot 2018-10-01 at 17 01 42](https://user-images.githubusercontent.com/1591802/46297288-a6465f80-c59c-11e8-9612-bba32032e4d2.png)
