### ISSUE TITLE
ControlPanel: Crews List

### ISSUE THREAD

**Issue by gianlucadelgobbo** [gianlucadelgobbo/AVnode.net#141]
missing images in the list

remove the delete option

Add new:
name & slug(check) required
POST HERE http://localhost:8006/admin/api/crews/new

**Comment by piero80** [comment]
---missing images in the list---
Url image? Now I take the imageFormat Url in http://localhost:8006/admin/api/crews

**Comment by gianlucadelgobbo** [comment]
DONE
