### ISSUE TITLE
ControlPanel: Crews Public

### ISSUE THREAD

**Issue by gianlucadelgobbo** [gianlucadelgobbo/AVnode.net#142]
Serverside errors are ignored

Validation data not coming from config.json

Apply client slug check

Direct link do not works
http://localhost:8006/admin/crews/5a9c321d606624000000b340/public

**Comment by piero80** [comment]
Hi @gianlucadelgobbo ,
We just fixed the direct link issue, not only for this section but even for all the others. 

We fixed also the issue relative to displaying the server error message. This is valid for any kind of server-error. In the image you can see a fake error we forced to test the functionality.

<img width="638" alt="screen shot 2018-10-10 at 19 34 02" src="https://user-images.githubusercontent.com/1591103/46754795-a1cc2600-ccc3-11e8-9093-ca2c7912d4c5.png">

**Comment by piero80** [comment]
The screenshot is relative to the Performance section, but it works also in Crew

**Comment by piero80** [comment]
Apply client slug check ---- Now is checked but the API is missed. 
Now return a fake API with an object slug-1 
![crew](https://user-images.githubusercontent.com/1591103/46795912-9b818c80-cd4b-11e8-8207-cb1da1103d5c.jpg)

**Comment by gianlucadelgobbo** [comment]
check slug on keyinput > 2 (no check on slug length, possible?)

CREW ADD si è rotta non appende l'id della persona da aggiungere
