### ISSUE TITLE
Crew Members Error Server Side

### ISSUE THREAD

**Issue by piero80** [gianlucadelgobbo/AVnode.net#143]
The Structure of the server side error should be similar to this.
```javascript
{
          response: {
            data: {
              message : "MEMBER_IS_NOT_A_MEMBER"
            }
          }
        }
```

**Comment by piero80** [comment]
There is an error when I adding or remove members already present
<img width="959" alt="screen shot 2018-11-04 at 12 46 59" src="https://user-images.githubusercontent.com/1591103/47963701-f5fec780-e02f-11e8-8bab-202e59ea7e8c.png">

**Comment by gianlucadelgobbo** [comment]
Solved
