### ISSUE TITLE
ControlPanel: Performances

### ISSUE THREAD

**Issue by gianlucadelgobbo** [gianlucadelgobbo/AVnode.net#144]
LIST
remove delete

NEW
Error: Missing title

IMAGES, GALLERIES, VIDEOS (all forms)
JS error

PUBLIC DATA
change
/admin/api/getmembers/:q
to
'/admin/api/getauthors/:q

Type, use this
/admin/api/getcategories/performances/slug/type

If son length you add a select with son and another select with this
/admin/api/getcategories/performances/slug/genre

Performance Url, add the full  real path on the bottom of the field? (all forms)

Is Public, miss the checkbox

tech_arts tech_reqs, not displaying existing contents, ex:
here is
/admin/api/performances/5be99f7ff6fa498e11000102/public
here not
/admin/performances/5be99f7ff6fa498e11000102/public

**Comment by piero80** [comment]
If son length you add a select with son and another select with this
/admin/api/getcategories/performances/slug/genre

Puoi spiegarlo meglio, non ho capito cosa bisogna fare?

**Comment by gianlucadelgobbo** [comment]
<img width="653" alt="screen shot 2018-12-13 at 14 29 25" src="https://user-images.githubusercontent.com/1591802/49941723-a55a7400-fee3-11e8-8e1f-44ee88cad556.png">
<img width="654" alt="screen shot 2018-12-13 at 14 29 40" src="https://user-images.githubusercontent.com/1591802/49941724-a55a7400-fee3-11e8-932b-ea0c6f7bc668.png">
<img width="655" alt="screen shot 2018-12-13 at 14 29 59" src="https://user-images.githubusercontent.com/1591802/49941725-a5f30a80-fee3-11e8-95d3-65e1077c2211.png">

**Comment by gianlucadelgobbo** [comment]
genre is the same for all types that have a sons

**Comment by piero80** [comment]
PUBLIC DATA
change
/admin/api/getmembers/:q
to
'/admin/api/getauthors/:q

Manca API SAVE AUTHORS
Manca API ADD NEW PERFORMANCE

**Comment by gianlucadelgobbo** [comment]
API ADD AUTHOR
/admin/api/:sez/:id/users/add/:id
EX:
/admin/api/performances/5be99f7ff6fa498e11000102/users/add/5be8735bfc396100000048fc

API REMOVE AUTHOR
/admin/api/:sez/:id/users/remove/:id  // **[API NOT FOUND CHECK IF EXISTS](http://localhost:8006/admin/api/performances/5be99f7ff6fa498e110000fb/users/remove/5be877a1fc39610000007367)**
EX:
/admin/api/performances/5be99f7ff6fa498e11000102/users/remove/5be8735bfc396100000048fc

API ADD NEW PERFORMANCE
DONE RETURN NEW ID

GALLERY
Add "slug"
Remove upload
API ADD NEW GALLERY (POST)
/admin/api/:sez/:id/galleries
DONE RETURN NEW GALLERY ID

http://localhost:8006/admin/performances/5be9a268f6fa498e110041d5/galleries

VIDEOS
Add "slug"
Remove upload
API ADD NEW VIDEO (POST)
/admin/api/:sez/:id/videos
DONE RETURN NEW VIDEO ID

http://localhost:8006/admin/performances/5be9a268f6fa498e110041d5/videos

**Comment by piero80** [comment]
Category API should have this model
```
[
{title:"category1",value:"category1",key:"0", 
children:[ 
{title:"children1", value:"children1", key:"0-1"},
{title:"children2", value:"children2", key:"0-2", children:[{title:'children.children'.....}]}
]}
]
```

**Comment by gianlucadelgobbo** [comment]
> Category API should have this model
> 
> ```
> [
> {title:"category1",value:"category1",key:"0", 
> children:[ 
> {title:"children1", value:"children1", key:"0-1"},
> {title:"children2", value:"children2", key:"0-2", children:[{title:'children.children'.....}]}
> ]}
> ]
> ```

DONE

**Comment by takehikotakehiko** [comment]
add new author in the performance do not work good, if i type single letters, and i select from the menu an option, it work. but if i type complete name and do not select from the list, it appear as selected, but saving do not work.

**Comment by takehikotakehiko** [comment]
category do not allow to select anything.

**Comment by takehikotakehiko** [comment]
it require a price, please remove totally this feature.

**Comment by takehikotakehiko** [comment]
saving performance drive user to the top of the page, without giving any feedback, but it create the performance, so if they misunderstood if they saved or not, they will create toons of performances with same name, i create for myselft 3 performances with same name in 3 seconds, becouse i do not get this.

**Comment by takehikotakehiko** [comment]
and there is not a way to delete them
