### ISSUE TITLE
General

### ISSUE THREAD

**Issue by gianlucadelgobbo** [gianlucadelgobbo/AVnode.net#147]
Check slug on keyinput > 2 (no check on slug length, possible?)

Phone Type component
- error on delete when is only one (is possible to just make it empty)
- on save please delete the full node no just .url

**Comment by Soniasalme** [comment]
Multi-Language fill tab it's not working (it only works in Italian)

**Comment by gianlucadelgobbo** [comment]
> Multi-Language fill tab it's not working (it only works in Italian)

SOLVED

**Comment by gianlucadelgobbo** [comment]
PROFILE_URL_HELP
Not working

**Comment by gianlucadelgobbo** [comment]
http://localhost:8006/signup/ wrong loader have to be the same of http://localhost:8006/signup
