### ISSUE TITLE
New Account (birthday)

### ISSUE THREAD

**Issue by gianlucadelgobbo** [gianlucadelgobbo/AVnode.net#149]
Single have to be blue (and selected) otherwise lets hide the single form

Change Component for birthday
Ops... UserTemp validation failed: birthday: Cast to Date failed for value "Invalid Date" at path "birthday"

**Comment by gianlucadelgobbo** [comment]
Component for birthday
https://reactdatepicker.com/#example-34

**Comment by ellisant** [comment]
on saving nothing happen

**Comment by ellisant** [comment]
> on saving nothing happen

on saving no feedback message

**Comment by takehikotakehiko** [comment]
this still do not work
same problem with birthday.

**Comment by takehikotakehiko** [comment]
the problem is still alive, it is impossible create an account if there is an error with birthday.
