### ISSUE TITLE
Multi-language management

### ISSUE THREAD

**Issue by brucelane** [gianlucadelgobbo/AVnode.net#15]
Based on the locale in the user schema.
Automatic translation plugin
Apple data?

**Comment by gianlucadelgobbo** [comment]
i18n for the labels
text description in the database
session managed from user preferences (if logged)
session managed from user choice (also if logged)
on flxer we use subdomains //it.flxer.net  //fr.flxer.net

**Comment by brucelane** [comment]
do you need subdomains like flxer?
could it be just a setting in the user profile?

**Comment by gianlucadelgobbo** [comment]
no because if you are not registered how you change the language?

**Comment by gianlucadelgobbo** [comment]
subdomains can work, any other proposal?

**Comment by brucelane** [comment]
well there is a setting in the user profile and, on the frontend, there could be a language dropdown/button...
subdomains are a bit more difficult to achieve

**Comment by gianlucadelgobbo** [comment]
exactly, a drop down, but for seo I think subdomain makes no difference, neither for node/us I suppose, why you see a problem on subdomains?

**Comment by brucelane** [comment]
it's not a problem, but it take more time to achieve
