### ISSUE TITLE
ControlPanel: Events

### ISSUE THREAD

**Issue by gianlucadelgobbo** [gianlucadelgobbo/AVnode.net#154]
LIST
- REMOVE DELETE

ADD NEW
- Missing slug
- slug check
`/api/:sez/new/slugs/:slug`
`/admin/api/events/new/slugs/bella`

EDIT
`/admin/events/5be99f93f6fa498e110003ef/public`
`/events/lpm-2018-rome`

PUBLIC DATA
- No server side errors shown
- Unable to save
- Categories is empty
`/admin/api/getcategories/events/slug/event-categories`
- Invalid date
- slug check
`/api/:sez/:id/public/slugs/:slug`
`/admin/api/events/5be99f93f6fa498e110003ef/public/slugs/bella`
- Add AUTHORS as in Performances

MY IMAGE
POST ON undefined id
/admin/api/events/undefined/image

PARTNERS
- NOT WORKING

PROGRAM (lets talk about it to make it simple for now)
- NOT WORKING

VIDEO & GALLERY AS IN PERFORMANCES

CALLS
- HIDE

SETTINGS
- Public not working

**Comment by takehikotakehiko** [comment]
what is a SLUG?



![immagine](https://user-images.githubusercontent.com/15085744/51430231-7341dd80-1c18-11e9-9172-ed56d28d2cc6.png)

**Comment by takehikotakehiko** [comment]
remove this trash bin icon or i remove all past LPM events just for fun. 
![immagine](https://user-images.githubusercontent.com/15085744/51430383-1c89d300-1c1b-11e9-80ef-55891e2cce35.png)

**Comment by piero80** [comment]
IN LIST REMOVE DELETE => DONE
ADD NEW => DONE
VIDEO & GALLERY => DONE
