### ISSUE TITLE
partecipate event privacy data

### ISSUE THREAD

**Issue by takehikotakehiko** [gianlucadelgobbo/AVnode.net#155]
in if i try to partecipate to lpm 2019, after selecting the category, and clicking next, appear this message for problem of safety privacy data
![immagine](https://user-images.githubusercontent.com/15085744/51430681-07af3e80-1c1f-11e9-84d2-5e1be5bb9984.png)
if i press continue, the page loading and come back to same page, there is no a way to arrive to terms and continue to the submission.

**Comment by gianlucadelgobbo** [comment]
FIXED
