### ISSUE TITLE
control panel edit profile

### ISSUE THREAD

**Issue by takehikotakehiko** [gianlucadelgobbo/AVnode.net#156]
when i open the control panel to edit profile, it open as blank screen, with this addess: https://avnode.net/admin/profile/5be87c63fc39610000009413/public

 it will be more nice if it open the profile section as first, like this https://avnode.net/admin/profile/public

**Comment by gianlucadelgobbo** [comment]
where you have found this link?
https://avnode.net/admin/profile/5be87c63fc39610000009413/public

**Comment by takehikotakehiko** [comment]
with the really big red button edit on my profile
![immagine](https://user-images.githubusercontent.com/15085744/51555510-09277380-1e78-11e9-9b7f-09dbf344983c.png)
