### ISSUE TITLE
partecipate cookies problem

### ISSUE THREAD

**Issue by takehikotakehiko** [gianlucadelgobbo/AVnode.net#158]
the link to partecipate to the lpm:
https://avnode.net/events/lpm-2019-rome/participate/
drive me to step 8
![immagine](https://user-images.githubusercontent.com/15085744/51490203-d3688900-1daa-11e9-94af-e48d24be8c9b.png)

every step i press it drive me to step 1, but the adree bar give me wrong data...
![immagine](https://user-images.githubusercontent.com/15085744/51490279-162a6100-1dab-11e9-88c4-6ea9128ba3bb.png)

**Comment by gianlucadelgobbo** [comment]
DONE!!!
