### ISSUE TITLE
mapping performances

### ISSUE THREAD

**Issue by takehikotakehiko** [gianlucadelgobbo/AVnode.net#159]
i have many mapping on my past performances, but i can't subscribe them to the new lpm, it give me this error: 
THERE ARE SOME ERRORS
Warning: You have no performance eligible for the call selected. Please create a performance and come back.

maybe the new mapping performances have different ID

all other 3 sections seem to be able to load my past performances.

**Comment by gianlucadelgobbo** [comment]
YOUR ARE:
Type: VJ Set  Tecnique: Mapping

Selection is made for Types, lets talk about it
