### ISSUE TITLE
register

### ISSUE THREAD

**Issue by takehikotakehiko** [gianlucadelgobbo/AVnode.net#161]
if i'm not logged in and i go to this page:
https://avnode.net/events/lpm-2019-rome/participate/
there are 2 buttons, login and register
register drive me here: https://avnode.net/signup/?returnTo=/events/lpm-2019-rome/participate/
but this page doen't work becouse i'm not logged in, i can compile everything but it is not recorded nowhere.
the register button have to drive people here:
https://avnode.net/signup
where i can create an account.

**Comment by gianlucadelgobbo** [comment]
DONE!!!
