### ISSUE TITLE
start date lpm2019

### ISSUE THREAD

**Issue by takehikotakehiko** [gianlucadelgobbo/AVnode.net#162]
![immagine](https://user-images.githubusercontent.com/15085744/51523717-9218bd80-1e2c-11e9-837a-f36dc7611de9.png)
lpm 2019 inizia a settembre 2020?

**Comment by takehikotakehiko** [comment]
also, time do not need seconds, hours and minuts will fit all our needs.

**Comment by gianlucadelgobbo** [comment]
DONE!!!
