### ISSUE TITLE
strange things on a crew

### ISSUE THREAD

**Issue by takehikotakehiko** [gianlucadelgobbo/AVnode.net#163]
strange things happens
an user told me he create a crew called "smode"
i can't find them in the recent crew page
https://avnode.net/performers/crews/mostrecent/
neighter with the search feature.

but he exist: here is the link he give me
https://avnode.net/smode

and if i try to click on the crew icon on the bottom of the page, it drive me to this:
https://avnode.net/https://smode.fr//
istead this:
https://avnode.net/smode/crews

also my crew page have some problem:
https://avnode.net/takehiko/crews
do not show anything...

but if i manually type this:
https://avnode.net/takehiko/crews/page/1
it work...

**Comment by gianlucadelgobbo** [comment]
i can't find them in the recent crew page
crew have to have at least 1 activity

used a slug https://smode.fr/ that is wrong (fixed)

https://avnode.net/takehiko/crews
fixed
