### ISSUE TITLE
FrontEnd: Gallery

### ISSUE THREAD

**Issue by brucelane** [gianlucadelgobbo/AVnode.net#20]
List and details.
Based on schema defined on https://github.com/gianlucadelgobbo/AVnode.net/issues/9
Galleries are linked to users, crews, events, etc

**Comment by gianlucadelgobbo** [comment]
perfect

**Comment by brucelane** [comment]
galleries: [{ type : Schema.ObjectId, ref : 'Gallery' }] added for users, crews, events, performances
