### ISSUE TITLE
Freezed version of EVENT

### ISSUE THREAD

**Issue by brucelane** [gianlucadelgobbo/AVnode.net#24]
Freez the event context for future reference.
Images, performences, user/crew context, ...
URI should be fixed for sharing on social networks

**Comment by gianlucadelgobbo** [comment]
text out of topic
freezed version is related to a past event that have not to change if a performer change something after the event ex: change the text or image on his user or of a performance

**Comment by fidelio314** [comment]
When changing data related to  an event (ex: name of performer) the past Event Data must remaine intact.
After the Event is passed an action must be created to save all the Data of an event as they are on that moment. (freezed version)

**Comment by gianlucadelgobbo** [comment]
On administrator of the event action (chechbox/button)

**Comment by brucelane** [comment]
Until now, when we edit an event we got this url  : /account/events/59d2a9c3ee09db1594b5cee2
I can add a slug input text in the form to define the exact url that will be used for the freezed event.
It becomes the url that is used before and after the event is freezed.
