### ISSUE TITLE
Sendy integration

### ISSUE THREAD

**Issue by brucelane** [gianlucadelgobbo/AVnode.net#26]
Use Sendy's API to send newsletters

**Comment by gianlucadelgobbo** [comment]
storage of the subscribers is coming from the avnode users, they will manage subscriptions from avnode

**Comment by fidelio314** [comment]
ok must create other issues to complete this feature description

**Comment by gianlucadelgobbo** [comment]
Now on flxer we use the api of mailchimp to let the use subscribe to newsletter or unsubscribe
![screen shot 2017-09-12 at 12 22 44](https://user-images.githubusercontent.com/1591802/30321098-2895a2b4-97b5-11e7-9a5c-23c945d2b75b.png)
As first step this is enought

**Comment by fidelio314** [comment]
hello @gianlucadelgobbo ! could you give more infor on this matter? as i can see you already instaled sendy on your server? can i have the username/password? 

what is exaclty the need for this issue? to synhronise the performers and creuw emails with sendy?
do you need to created different lists of subscribers?

thanks

panos
