### ISSUE TITLE
ControlPanel: Event | Schema modification and forms update

### ISSUE THREAD

**Issue by gianlucadelgobbo** [gianlucadelgobbo/AVnode.net#32]
[https://github.com/avnode/avnode/blob/master/lib/models/Event.js](url)

Some notes:

`creation_date: Date,` is stored somewhere?

    starts: Date,
    ends: Date,

what happen for a festival on 2 weekend? is not better to have a something like this for each day?

    [
      {
        starts: Date, 
        ends: Date,
      }
    ]    

`about: String,` we need it multilang

`address: String,` we don't need, venues is ok 

`website: String,` can be multiple and we manage with this social media links?

What about something like that?

instead of:

    emails: [{
      email: String,
      is_public: {type: Boolean, default: false},
      is_primary: {type: Boolean, default: false},
      is_confirmed: { type: Boolean, default: false },
      confirm: String
    }],
    website: String,
    phonenumbers: [], 
    messengers: [],

we could use:

    contacts: [{
      ID: String,
      type: String, //email, phone, skype, websites, socials
      is_public: {type: Boolean, default: false},
      is_primary: {type: Boolean, default: false},
      is_confirmed: { type: Boolean, default: false },
      confirm: String
    }],

`is_open` is it for the open call?

`eventSchema.virtual('organizers', {` is this the creator?

`eventSchema.virtual('organizing_crews', {` we need to add a category on this relation, something like:

    eventSchema.virtual('partners', {
      ref: 'Partner',
      localField: '_id',
      foreignField: 'events'
    });
    Partner {
      _id:Crew,
      partnership_type: [partnership_types]
    });

`eventSchema.virtual('performances', {` this is ok till the performance is not scheduled, once scheduled we need to add some info on this relation, something like:

    eventSchema.virtual('programme', {
      ref: 'Slot',
      localField: '_id',
      foreignField: 'events'
    });
    Slot {
      _id:Performance,
      schedule: {
        date: Date,
        starttime: Date,
        endtime: Date,
        venue: Venue,
        event_category:[event_categories],
        day:String,
        room:String
      }
    });

Programming is available only if you set this:

    organizationsettings: {
      program_builder: Boolean,
      advanced_proposals_manager: Boolean,
      call: {
        is_active: Boolean,
        program_builder: Boolean,
        advanced_proposals_manager: Boolean,
        next_edition: String,
        header_image: String,
        background_image: String,
        background_color: String,
        calls: [{
          title: String,
          email: String,
          permalink: String,
          start_date: Date,
          end_date: Date,
          admitted: [String],
          excerpt: String,
          terms: String,
          topics: [{
            title: String,
            description: String
          }],
          packages: [{
            title: String,
            price: Number,
            description: String,
            personal: Boolean,
            requested: Boolean,
            allow_multiple: Boolean,
            allow_options: Boolean,
            daily: {
              start_date: Date,
              end_date: Date
            }
          }]
        }]
      },
      permissions: {
        administrator: [Usersummary], // FIXME
      }
    }

We need to manage galleries in some way

We need to add event categories in some way (Festival, meeting, one night etc)

What about likes, visits and shares?

**Comment by brucelane** [comment]
```about: String``` created with array of About schema, multilang
```links: [Link]``` created with array of Link schema, new name for emails or contacts

**Comment by gianlucadelgobbo** [comment]
we miss this:
```
[
  {
    starts: Date, 
    ends: Date,
    venue: Venue
  }
]   
```

**Comment by brucelane** [comment]
Event schema modified
