### ISSUE TITLE
GET a freezed EVENT DATA

### ISSUE THREAD

**Issue by fidelio314** [gianlucadelgobbo/AVnode.net#33]
Create an api ws that returns the EVENT object (json) 

Now we need the full object for every event, like this
https://flxer.net/api/lpm-team/events/lpm-2016-amsterdam/
for
https://flxer.net/lpm-team/events/lpm-2016-amsterdam/

**Comment by fidelio314** [comment]
@gianlucadelgobbo 
- do we need authentication for security? 
- the id is a kind of slug of the event? "lpm-2016-amsterdam"

**Comment by gianlucadelgobbo** [comment]
wrong issue, write here #25
