### ISSUE TITLE
FrontEnd: Playlist Download ZIP

### ISSUE THREAD

**Issue by fidelio314** [gianlucadelgobbo/AVnode.net#34]
As a (user?) or a visitor i can downlad the playlist into a zip file

**Comment by fidelio314** [comment]
@gianlucadelgobbo can a simple visitor download the zip of all videos of a playlist? or only avnode user can?

and if a playlist has 100 videos do you think is wise enable the download maybe of 1Terrabyte of data? this may cause big problems on the server.

**Comment by gianlucadelgobbo** [comment]
only avnode user can download
about size we can put a size limit of the playlist?
Anyway the storage can not be on us we have to find a partner as we finish the first step
