### ISSUE TITLE
ControlPanel: User | Schema modification and forms update

### ISSUE THREAD

**Issue by brucelane** [gianlucadelgobbo/AVnode.net#5]
From https://github.com/avnode/avnode/issues/3
Instead of:
```
emails: [{
  email: String,
  is_public: {type: Boolean, default: false},
  is_primary: {type: Boolean, default: false},
  is_confirmed: { type: Boolean, default: false },
  mailinglists: [],
  confirm: String
}],
website: String,
phonenumbers: [], 
messengers: [],
```
we could use:
```
contacts: [{
  ID: String,
  type: String, //email, phone, skype, websites, socials
  is_public: {type: Boolean, default: false},
  is_primary: {type: Boolean, default: false},
  is_confirmed: { type: Boolean, default: false },
  mailinglists: [],
  confirm: String
}],
website: String,
phonenumbers: [], 
messengers: [],
```

Add:
```surname: String,``` Missing
```about: String,``` we need it multilang
```citizenship: [],``` if more than one
```activity:``` Number, this could be useful to sort the default view (most active) and comes from a formula
```addresses: [address],``` Missing we could use address as venues as here https://github.com/avnode/avnode/issues/2
```roles: ????,``` For super admin at least?
```language: String,``` Missing
```connections: [],```

**Comment by brucelane** [comment]
I think we should keep emails structure because it manages: is_primary, is_confirmed, mailinglists, etc.
And **add** the contacts structure which I would rename to links:
```
links: [{
  id: String,
  type: String, //email, phone, skype, websites, socials
  is_public: {type: Boolean, default: false},
}]
```
You think id is the url ? 
Like if type is website id=http://.., if type is phone id=+336... ?

**Comment by gianlucadelgobbo** [comment]
yes but id is not a good name

About
is_primary it could wrok fro phones as for websites, why not social
is_confirmed works for phones and for websites, why not social if we manage wit this object the auth
mailinglists now works only on emails but tomorrow maybe we could have phone numbers for whatsapp and similars

Anyway is not a problem how to store that data, can be rearranged easily in anytime

**Comment by brucelane** [comment]
We keep is_primary, is_confirmed, mailinglists.
Let's add a url field

**Comment by brucelane** [comment]
```about: String``` done with array of About schema, multilang
```links: [Link]``` created with array of Link schema, new name for emails or contacts
Created:
surname: String
citizenship: []
activity: Number
addresses: [Address] Address schema
roles: []
language: String
connections: []

**Comment by brucelane** [comment]
galleries: [{ type : Schema.ObjectId, ref : 'Gallery' }] added

**Comment by brucelane** [comment]
Address: fields should be visible to allow the user to input only the fields he wants.
City and country are required, though

**Comment by brucelane** [comment]
TODO: remove countries from user object?

**Comment by brucelane** [comment]
can user address be public?
