### ISSUE TITLE
ControlPanel: User | Success/ERROR messagge missing on SAVE

### ISSUE THREAD

**Issue by gianlucadelgobbo** [gianlucadelgobbo/AVnode.net#93]
I can delete everything and save too

**Comment by brucelane** [comment]
for each form, I need for each field the validation rules (now I only know about the user surname and name required)

**Comment by gianlucadelgobbo** [comment]
neither you understand is is saving or not, for now use standard rules than we adjust it, in general in the config we can put min and max len for strings, email format for emails, phone format for phones, username no strange char

**Comment by brucelane** [comment]
we got validation rules in this file: https://github.com/gianlucadelgobbo/AVnode.net/blob/master/app/components/user/validate.js
I have to activate them in each form

**Comment by brucelane** [comment]
example on https://bruce.avnode.net/account/profile/private
try to remove name or surname

**Comment by gianlucadelgobbo** [comment]
ok it works but no alert, not visible no anchor

Instead if I put this works, but you have no success messagge on save, lets put something over with a progres than a messagge of success or error or is better to reload

Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book. It has survived not only five centuries, but also the leap into electronic typesetting, remaining essentially unchanged. It was popularised in the 1960s with the release of Letraset sheets containing Lorem Ipsum passages, and more recently with desktop publishing software like Aldus PageMaker including versions of Lorem Ipsum.
