### ISSUE TITLE
ControlPanel: User Public data | Location Old style

### ISSUE THREAD

**Issue by gianlucadelgobbo** [gianlucadelgobbo/AVnode.net#94]
where are all the nice adress info in the model?

**Comment by gianlucadelgobbo** [comment]
Seen that is in private data lets put here only the view with an edit button that goes on private data

**Comment by brucelane** [comment]
if if add an "edit button" we lose the state, the public data wouldn't be saved , I would prefer a message 'edit in private section, only the locality and country are displayed publicly'

**Comment by gianlucadelgobbo** [comment]
no edit button, edit link to Private data

**Comment by brucelane** [comment]
but we lose the unsaved date in Public data

**Comment by gianlucadelgobbo** [comment]
why?


Gianluca
______________________________________
Flyer communication
www.flyer.it
Via del Verano 39 - 00185 Roma
Tel. +39 06 78147301 Fax +39 06 78390805

**Comment by brucelane** [comment]
because save button is not clicked and we navigate to another page

**Comment by gianlucadelgobbo** [comment]
ah ok obvius... is ok

**Comment by brucelane** [comment]
fixed
