### ISSUE TITLE
ControlPanel: User Images | NO Thumbnail resizer

### ISSUE THREAD

**Issue by gianlucadelgobbo** [gianlucadelgobbo/AVnode.net#96]
I still see the old one

**Comment by brucelane** [comment]
thumbnail is from File/File migration at 55x55 dimensions
we got to discuss the image sizes for:
- thumbnail : square? 
- card (displayed in the frontend, homepage for example)
- teaser (frontend, teaser image for the performer on top)
- image: profile image
do we want to put the sizes in config/local.json and create those image sizes at runtime based on that getConfig?

**Comment by gianlucadelgobbo** [comment]
yes, put in the config the same size we already have from flxer

- Profile Image (only images max 5mb)
-- Thumbnail 55x55
-- Medium 280x210
-- Large 400x300

- Teaser image (only images max 11mb)
-- Medium 1280x720
-- Large 1920x1080
